FROM node:20

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application
COPY . .

# Expose port for Angular dev server
EXPOSE 4200

# Start Angular development server
CMD ["npm", "start"]